== The blended build image for Alpine

This image build on top of link:../zulu-8-alpine/ReadMe.adoc[zulu-8-alpine] and adds the following tools:

https://www.scala-sbt.org/[sbt 1.2.8]::
Required to execute any of the blended builds based on sbt.

https://nodejs.org/en/[node]::
The Node.JS execution environment for executing JavaScript from within sbt.

https://www.npmjs.com/[npm]::
The node package manager required to resolve JS dependencies with the
https://scalacenter.github.io/scalajs-bundler/[ScalaJSBundler]

https://yarnpkg.com/lang/en/[yarn]::
Optionally used by ScalaJSBundler as an advanced node dependency manager.

http://chromedriver.chromium.org/downloads[chromedriver]::
Installed, so that we can run headless tests for our browser applications.

=== Using the blended build image (on Linux using docker)

. Prepare your environment
.. Install http://www.docker.com[docker]
.. Create a group with an arbitrary name and the `GID 5000`. The group id is defined
   in `base-alpine` and could be changed if required. In the following steps we will assume
   that `${GRPNAME}` contains the name of the group.
.. Clone the repository to your machine. In the following steps we will assume that
   `${PRJ_DIR}` points to the directory containing the blended project.
.. Make sure `${PRJ_DIR}` belongs to `$(whoami):${GRPNAME}` and that group members
   have write access to the project directory.
. navigate to `${PRJ_DIR}`

With the setup above, a build can be run with:

```
docker run -u blended -it \
  -v $(pwd):/home/blended/project \
  atooni/build-alpine:1.0.1 /bin/bash -l -c "cd ~/project ; sbt test"
```

In the command above `sbt test` is the sbt command to be executed for the project and can be replaced
with any valid sbt command project understood by the project's sbt configuration.

=== Exposing the .ivy2 directory to the build image

In order to avoid downloading all dependencies everytime the image is restarted, the `~/.ivy2` directory
can be exposed to the docker container as follows:

```
docker run -u blended -it \
  -v $(pwd):/home/blended/project \
  -v /home/andreas/.ivy2:/home/blended/.ivy2 \
  atooni/build-alpine:1.0.1 /bin/bash -l -c "cd ~/project ; sbt publishLocal"
```

Again, `~/.ivy2` must belong to `${GRPNAME}` and must have group write permissions. In the example above,
all published artifacts will end up in the directory `~/.ivy2`.

=== Supported projects to be used with the build container

* https://github.com/woq-blended/blended[blended framework]
* https://github.com/woq-blended/blended.itestsupport[blended integration test support]
* https://github.com/woq-blended/blended.mgmt.ui[blended management UI]
